# prediksi harga saham Regresion

Dataset: https://www.kaggle.com/datasets/jacksoncrow/stock-market-dataset

### Dependencies:
* !pip install numpy
* !pip install pandas
* !pip install tensorflow
* !pip install scikit-learn

## Data Preprocessing

### Import the libraries

In [4]:
pip install numpy pandas scikit-learn joblib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for tensorflow


In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import confusion_matrix, accuracy_score

ModuleNotFoundError: No module named 'tensorflow'

### Importing the dataset

In [8]:
data = pd.read_csv('symbols_valid_meta.csv')
data

Nasdaq Traded Symbol                                      Security Name  \
0                Y      A            Agilent Technologies, Inc. Common Stock   
1                Y     AA                    Alcoa Corporation Common Stock    
2                Y   AAAU                       Perth Mint Physical Gold ETF   
3                Y   AACG  ATA Creativity Global - American Depositary Sh...   
4                Y   AADR                AdvisorShares Dorsey Wright ADR ETF   
...            ...    ...                                                ...   
8044             Y    ZUO                   Zuora, Inc. Class A Common Stock   
8045             Y    ZVO                          Zovio Inc. - Common Stock   
8046             Y   ZYME                       Zymeworks Inc. Common Shares   
8047             Y   ZYNE       Zynerba Pharmaceuticals, Inc. - Common Stock   
8048             Y   ZYXI                         Zynex, Inc. - Common Stock   

     Listing Exchange Market Category ETF  Round Lot Size Test Issue  \
0                   N                   N           100.0          N   
1                   N                   N           100.0          N   
2                   P                   Y           100.0          N   
3                   Q               G   N           100.0          N   
4                   P                   Y           100.0          N   
...               ...             ...  ..             ...        ...   
8044                N                   N           100.0          N   
8045                Q               Q   N           100.0          N   
8046                N                   N           100.0          N   
8047                Q               G   N           100.0          N   
8048                Q               S   N           100.0          N   

     Financial Status CQS Symbol NASDAQ Symbol NextShares  
0                 NaN          A             A          N  
1                 NaN         AA            AA          N  
2                 NaN       AAAU          AAAU          N  
3                   N        NaN          AACG          N  
4                 NaN       AADR          AADR          N  
...               ...        ...           ...        ...  
8044              NaN        ZUO           ZUO          N  
8045                N        NaN           ZVO          N  
8046              NaN       ZYME          ZYME          N  
8047                N        NaN          ZYNE          N  
8048                N        NaN          ZYXI          N  

[8049 rows x 12 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8049 entries, 0 to 8048
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Nasdaq Traded     8049 non-null   object 
 1   Symbol            8049 non-null   object 
 2   Security Name     8049 non-null   object 
 3   Listing Exchange  8049 non-null   object 
 4   Market Category   8049 non-null   object 
 5   ETF               8049 non-null   object 
 6   Round Lot Size    8049 non-null   float64
 7   Test Issue        8049 non-null   object 
 8   Financial Status  3383 non-null   object 
 9   CQS Symbol        4666 non-null   object 
 10  NASDAQ Symbol     8049 non-null   object 
 11  NextShares        8049 non-null   object 
dtypes: float64(1), object(11)
memory usage: 754.7+ KB


## Cleaning the dataset

In [10]:
# check null
data.isnull().sum()

Nasdaq Traded          0
Symbol                 0
Security Name          0
Listing Exchange       0
Market Category        0
ETF                    0
Round Lot Size         0
Test Issue             0
Financial Status    4666
CQS Symbol          3383
NASDAQ Symbol          0
NextShares             0
dtype: int64

In [11]:
# check duplicate
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
8044    False
8045    False
8046    False
8047    False
8048    False
Length: 8049, dtype: bool

In [12]:
# check baris yg duplicate
data[data.duplicated()]

Empty DataFrame
Columns: [Nasdaq Traded, Symbol, Security Name, Listing Exchange, Market Category, ETF, Round Lot Size, Test Issue, Financial Status, CQS Symbol, NASDAQ Symbol, NextShares]
Index: []

In [13]:
# check jumlah baris yg duplicated
data.duplicated().sum()

0

In [14]:
# drop duplicate
data.drop_duplicates(inplace=True)

In [15]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
8044    False
8045    False
8046    False
8047    False
8048    False
Length: 8049, dtype: bool

In [16]:
# check jumlah baris yg duplicated
data.duplicated().sum()

0

## Encoding Nasdaq Traded data

In [17]:
data['Nasdaq Traded'].value_counts()

Nasdaq Traded
Y    8049
Name: count, dtype: int64

In [18]:
# do label encoding
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['Nasdaq Traded'] = label_encoder.fit_transform(data['Nasdaq Traded'])
data

Nasdaq Traded Symbol                                      Security Name  \
0                 0      A            Agilent Technologies, Inc. Common Stock   
1                 0     AA                    Alcoa Corporation Common Stock    
2                 0   AAAU                       Perth Mint Physical Gold ETF   
3                 0   AACG  ATA Creativity Global - American Depositary Sh...   
4                 0   AADR                AdvisorShares Dorsey Wright ADR ETF   
...             ...    ...                                                ...   
8044              0    ZUO                   Zuora, Inc. Class A Common Stock   
8045              0    ZVO                          Zovio Inc. - Common Stock   
8046              0   ZYME                       Zymeworks Inc. Common Shares   
8047              0   ZYNE       Zynerba Pharmaceuticals, Inc. - Common Stock   
8048              0   ZYXI                         Zynex, Inc. - Common Stock   

     Listing Exchange Market Category ETF  Round Lot Size Test Issue  \
0                   N                   N           100.0          N   
1                   N                   N           100.0          N   
2                   P                   Y           100.0          N   
3                   Q               G   N           100.0          N   
4                   P                   Y           100.0          N   
...               ...             ...  ..             ...        ...   
8044                N                   N           100.0          N   
8045                Q               Q   N           100.0          N   
8046                N                   N           100.0          N   
8047                Q               G   N           100.0          N   
8048                Q               S   N           100.0          N   

     Financial Status CQS Symbol NASDAQ Symbol NextShares  
0                 NaN          A             A          N  
1                 NaN         AA            AA          N  
2                 NaN       AAAU          AAAU          N  
3                   N        NaN          AACG          N  
4                 NaN       AADR          AADR          N  
...               ...        ...           ...        ...  
8044              NaN        ZUO           ZUO          N  
8045                N        NaN           ZVO          N  
8046              NaN       ZYME          ZYME          N  
8047                N        NaN          ZYNE          N  
8048                N        NaN          ZYXI          N  

[8049 rows x 12 columns]

## Mapping Market Category history

In [19]:
# mapping untuk Market Category
data['Market Category'].value_counts()

Market Category
     4666
Q    1531
S     952
G     900
Name: count, dtype: int64

In [20]:
Market_Category_maping = {'never': 0, 'No Info': -1, 'current':2, 'not current': 0, 'former' : 1, 'ever': 2}
data['Market Category'] = data['Market Category'].map(Market_Category_maping)
data

Nasdaq Traded Symbol                                      Security Name  \
0                 0      A            Agilent Technologies, Inc. Common Stock   
1                 0     AA                    Alcoa Corporation Common Stock    
2                 0   AAAU                       Perth Mint Physical Gold ETF   
3                 0   AACG  ATA Creativity Global - American Depositary Sh...   
4                 0   AADR                AdvisorShares Dorsey Wright ADR ETF   
...             ...    ...                                                ...   
8044              0    ZUO                   Zuora, Inc. Class A Common Stock   
8045              0    ZVO                          Zovio Inc. - Common Stock   
8046              0   ZYME                       Zymeworks Inc. Common Shares   
8047              0   ZYNE       Zynerba Pharmaceuticals, Inc. - Common Stock   
8048              0   ZYXI                         Zynex, Inc. - Common Stock   

     Listing Exchange  Market Category ETF  Round Lot Size Test Issue  \
0                   N              NaN   N           100.0          N   
1                   N              NaN   N           100.0          N   
2                   P              NaN   Y           100.0          N   
3                   Q              NaN   N           100.0          N   
4                   P              NaN   Y           100.0          N   
...               ...              ...  ..             ...        ...   
8044                N              NaN   N           100.0          N   
8045                Q              NaN   N           100.0          N   
8046                N              NaN   N           100.0          N   
8047                Q              NaN   N           100.0          N   
8048                Q              NaN   N           100.0          N   

     Financial Status CQS Symbol NASDAQ Symbol NextShares  
0                 NaN          A             A          N  
1                 NaN         AA            AA          N  
2                 NaN       AAAU          AAAU          N  
3                   N        NaN          AACG          N  
4                 NaN       AADR          AADR          N  
...               ...        ...           ...        ...  
8044              NaN        ZUO           ZUO          N  
8045                N        NaN           ZVO          N  
8046              NaN       ZYME          ZYME          N  
8047                N        NaN          ZYNE          N  
8048                N        NaN          ZYXI          N  

[8049 rows x 12 columns]

## Checking age data

In [21]:
data.describe()

Nasdaq Traded  Market Category  Round Lot Size
count         8049.0              0.0     8049.000000
mean             0.0              NaN       99.942974
std              0.0              NaN        2.289194
min              0.0              NaN        1.000000
25%              0.0              NaN      100.000000
50%              0.0              NaN      100.000000
75%              0.0              NaN      100.000000
max              0.0              NaN      100.000000

In [22]:
# data[data['Symbol'] < 1]
data['Symbol'].dtype

dtype('O')

In [23]:
data['Symbol'] = pd.to_numeric(data['Symbol'], errors='coerce')

In [24]:
data[data['Symbol'] < 1]

Empty DataFrame
Columns: [Nasdaq Traded, Symbol, Security Name, Listing Exchange, Market Category, ETF, Round Lot Size, Test Issue, Financial Status, CQS Symbol, NASDAQ Symbol, NextShares]
Index: []

In [25]:
data[data['Symbol'] > 1]


Empty DataFrame
Columns: [Nasdaq Traded, Symbol, Security Name, Listing Exchange, Market Category, ETF, Round Lot Size, Test Issue, Financial Status, CQS Symbol, NASDAQ Symbol, NextShares]
Index: []

In [26]:
data['Symbol'].value_counts()

Series([], Name: count, dtype: int64)

In [27]:
# hapus data age yg kurang dari 1 (hanya memuat age > 1)
data = data[data['Symbol'] > 1]

In [28]:
data['Symbol'].value_counts()

Series([], Name: count, dtype: int64)

In [29]:
# convert age to int
data['Symbol'] = data['Symbol'].astype(int)

In [30]:
data['Symbol'].value_counts()

Series([], Name: count, dtype: int64)

In [31]:
data.describe()

Nasdaq Traded  Symbol  Market Category  Round Lot Size
count            0.0     0.0              0.0             0.0
mean             NaN     NaN              NaN             NaN
std              NaN     NaN              NaN             NaN
min              NaN     NaN              NaN             NaN
25%              NaN     NaN              NaN             NaN
50%              NaN     NaN              NaN             NaN
75%              NaN     NaN              NaN             NaN
max              NaN     NaN              NaN             NaN

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Nasdaq Traded     0 non-null      int32  
 1   Symbol            0 non-null      int32  
 2   Security Name     0 non-null      object 
 3   Listing Exchange  0 non-null      object 
 4   Market Category   0 non-null      float64
 5   ETF               0 non-null      object 
 6   Round Lot Size    0 non-null      float64
 7   Test Issue        0 non-null      object 
 8   Financial Status  0 non-null      object 
 9   CQS Symbol        0 non-null      object 
 10  NASDAQ Symbol     0 non-null      object 
 11  NextShares        0 non-null      object 
dtypes: float64(2), int32(2), object(8)
memory usage: 0.0+ bytes


## Split train and test set

In [33]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print(y)

[]


In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Contoh data
# Misalnya, X adalah fitur dan y adalah target
X = pd.DataFrame({
    'Feature1': [1, 2, 3, 4, 5],
    'Feature2': [2, 4, 6, 8, 10]
})
y = pd.Series([0, 1, 0, 1, 0])

# Hapus baris yang memiliki nilai kosong (jika ada)
X = X.dropna()
y = y.dropna()

# Split data menjadi train dan test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)

# Menampilkan hasil
print(f"Jumlah data X_train: {len(X_train)}")
print(f"Jumlah data X_test: {len(X_test)}")
print(f"Jumlah data y_train: {len(y_train)}")
print(f"Jumlah data y_test: {len(y_test)}")

Jumlah data X_train: 4
Jumlah data X_test: 1
Jumlah data y_train: 4
Jumlah data y_test: 1


## Feature scaling

In [35]:
sc = preprocessing.StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
print(X_train)

[[-1.26491106 -1.26491106]
 [-0.63245553 -0.63245553]
 [ 0.63245553  0.63245553]
 [ 1.26491106  1.26491106]]


In [37]:
print(X_test)

[[0. 0.]]


## Training and predict the model using Logistic regression

In [38]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train) # y_train tidak scale krn diskret

LogisticRegression()

In [39]:
y_pred_lr = lr.predict(X_test) # X_test sudah di-scale

In [40]:
# logistic regression
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
accuracy_score(y_test, y_pred_lr)

[[1]]


c:\Users\ASUS\MSIB2024\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


1.0

## Training and predict the model using Linear SVM

In [41]:
from sklearn.svm import SVC
linear_svm = SVC(kernel = 'linear')
linear_svm.fit(X_train, y_train)

SVC(kernel='linear')

In [42]:
y_pred_svm = linear_svm.predict(X_test)

In [43]:
# Linear SVM
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
accuracy_score(y_test, y_pred_svm)

[[0 1]
 [0 0]]


0.0

## Training and predict the model kernel SVM

In [44]:
from sklearn.svm import SVC
classifier_kernel_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_kernel_svm.fit(X_train, y_train)
y_pred_kernel_svm = classifier_kernel_svm.predict(X_test)

In [45]:
# Kernel SVM
cm = confusion_matrix(y_test, y_pred_kernel_svm)
print(cm)
accuracy_score(y_test, y_pred_kernel_svm)

[[0 1]
 [0 0]]


0.0

## Training and predict the model Naive Bayes

In [46]:
from sklearn.naive_bayes import GaussianNB
classifier_naive_bayes = GaussianNB()
classifier_naive_bayes.fit(X_train, y_train)
y_pred_naive_bayes = classifier_naive_bayes.predict(X_test)

In [47]:
# naive bayes
cm = confusion_matrix(y_test, y_pred_naive_bayes)
print(cm)
accuracy_score(y_test, y_pred_naive_bayes)

[[0 1]
 [0 0]]


0.0

## Training and predict the model Decision Tree

In [48]:
from sklearn.tree import DecisionTreeClassifier
classifier_decision_tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_decision_tree.fit(X_train, y_train)
y_pred_decision_tree = classifier_decision_tree.predict(X_test)

In [49]:
# decision tree
cm = confusion_matrix(y_test, y_pred_decision_tree)
print(cm)
accuracy_score(y_test, y_pred_decision_tree)

[[0 1]
 [0 0]]


0.0

## Training and predict the model Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
classifier_random_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_random_forest.fit(X_train, y_train)
y_pred_random_forest = classifier_random_forest.predict(X_test)

In [51]:
# random forest
cm = confusion_matrix(y_test, y_pred_random_forest)
print(cm)
accuracy_score(y_test, y_pred_random_forest)

[[0 1]
 [0 0]]


0.0

## Building the ANN

### Initializing the ANN

In [52]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [53]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [54]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [55]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Training the ANN

### Compiling the ANN

In [56]:
# ann.compile(optimizer='adam', loss = 'mean_squared_error') # regression
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'] )

### Training the ANN model on the Training set

In [57]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.8193
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.8175
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5000 - loss: 0.8157
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.8139
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.8121
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.8103
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.8086
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5000 - loss: 0.8069
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.8052
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.8036
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.5000 - loss: 0.8020
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - lo

### Predicting the results of the Test set

In [58]:
import numpy as np

# Prediksi
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

# Mengubah y_test menjadi array NumPy
y_test = np.array(y_test)

# Menggabungkan prediksi dengan y_test
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
[[0 0]]


In [59]:
# ann
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1]]


c:\Users\ASUS\MSIB2024\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


1.0

## Best Result: Random Forest

### Save model (non Deep Learing)

In [60]:
# save model
import joblib
# Simpan model ke file
joblib.dump(classifier_random_forest, 'harga_saham_prediction.pkl')

# Muat model dari file
# loaded_model = joblib.load('diabetes_prediction.pkl')

['harga_saham_prediction.pkl']

### Save model (Deep Learing)

In [61]:
# saving model
ann.save('harga_saham_prediction.keras')
# tf.keras.models.save_model(filepath='churn model.keras', model=ann)

# load model
# saved_ann =  tf.keras.models.load_model('churn model.keras')